PRODUCT_CATALOG = {
    "POULTRY": {
        "5 Boiler (Hen)": "£19.99",
        "Chicken Drumsticks (Skin Off)": "£6.99",
        "Chicken Strips (1kg)": "£10.99",
        "Chicken Liver (1Kg)": "£5.99",
        "Mid Wings": "£6.99",
        "Chicken Oyster Thighs": "£4.99",
        "Chicken Gizzards (1Kg)": "£5.99",
        "Chicken Hearts (1Kg)": "£5.99",
        "Boiler (Hen)": "£4.99",
        "Chicken Breast": "£9.99",
        "Fire In The Hole Wings (20 pieces)": "£8.99",
        "Chicken Niblets": "£7.99",
        "Prime Wings": "£6.99",
        "Chicken Thigh Mince": "£8.99",
        "Chicken Wings 3 Joint": "£5.99",
        "Chicken Thigh Boneless": "£8.99",
        "Chicken Legs (Skin Off)": "£5.99",
        "Chicken Legs (Skin On)": "£4.99",
        "Chicken Drumsticks (Skin On)": "£5.99",
        "Premium Chicken Mince": "£8.99",
        "Whole Roaster Chicken 1300-1400 Gms": "£7.99",
        "Baby Chicken": "£5.99",
        "Spatch Cock Chicken (1100G)": "£6.99",
        "Chicken Feet (1kg bag)": "£4.99",
        "Tandoori Chicken 1100-1200 Gms": "£6.99",
        "Chicken Sausages in Blankets Party Pack (50pc)": "£16.99",
        "Tariq Halal Traditional Beef Sausages (with hint of pepper) 342g": "£3.99",
        "Halal Frozen Grade A Chicken (800g)": "£3.99 (Out of stock)",
        "Chicken Sausages in Blankets (12pc)": "£4.99",
        "Peri Peri Chicken Liver (1Kg)": "£6.99",
        "Peri Peri Chicken Sausages": "£2.99",
        "Paprika Chicken Cocktail Sausages": "£2.99",
        "Moroccan Lamb Sausages": "£3.99",
        "Chicken Breakfast Sausages": "£2.99",
        "Beef & Black Pepper Cocktail Sausages": "£2.99",
        "Veal Burger": "£2.99",
        "Frozen Halal Whole Turkey": "£34.99",
        "Lamb Burgers (4)": "£6.99",
        "Beef Burgers (4)": "£5.99",
        "Chicken Burgers (4)": "£5.99",
        "Superchick American Style Fillet Burger": "£11.99"
    },
    "LAMB": {
        "Whole Frozen Milk Fed Suckling Lamb Shoulder": "£19.99 (Out of stock)",
        "Whole Frozen Milk Fed Suckling Lamb Leg": "£19.99",
        "Haqeeqa Baby Lamb": "£350.00",
        "Lamb Tripe (Stomach)": "£2.00",
        "Lamb Tongue": "£9.99",
        "Lamb Testicles (Kapoorae)": "£7.99",
        "Lamb Kidneys": "£8.99",
        "Lamb Hearts": "£5.99",
        "Lamb Brain (Per Packet)": "£7.49",
        "Lamb Liver": "£5.99",
        "Lamb Head Without Skin": "£4.99",
        "Mutton Ribs": "£11.99",
        "Mutton Shanks (Niharri)": "£14.99",
        "Mutton Neck": "£11.99",
        "Mutton Back Chops": "£14.99",
        "Mutton Front Chops": "£14.99",
        "Mutton Shoulder": "£14.99",
        "Mutton Leg": "£14.99",
        "Baby Lamb Shoulder For Roasting 1.8-2.0 Kg (whole)": "£39.95",
        "Whole Lamb Leg for Roasting 2.5-2.8 Kg": "£54.95",
        "Baby Lamb French Rack": "£34.95",
        "3Kg Baby Lamb Mince Special": "£39.99",
        "Baby Lamb Leg Mince": "£24.99",
        "Baby Lamb Neck": "£14.99",
        "Baby Lamb Leg Steaks With Bone": "£21.99",
        "Half Baby Lamb (10kg Net Differs)": "£159.99",
        "Mutton Mince Up To 25% Fat": "£9.99",
        "Baby Lamb Mince (25% fat)": "£14.99",
        "Baby Lamb Shanks": "£19.99",
        "Baby Lamb Front Chops": "£23.99",
        "Haqeeqa Sheep": "£350.00",
        "Baby Mixed Lamb": "£19.95",
        "Mixed Mutton": "£12.99",
        "Baby Lamb Ribs": "£14.99",
        "Boneless Mutton": "£16.99",
        "Baby Lamb Back Chops": "£21.99",
        "Baby Lamb Boneless": "£24.99",
        "Baby Lamb Shoulder": "£22.99",
        "Baby Lamb Leg (1kg)": "£22.99",
        "Baby Lamb Leg Steaks Without Bone": "£24.99",
        "Whole Kid Goat (4Kg-5Kg)": "£95.00",
        "Whole Baby Lamb (20kg Net Differs)": "£299.99",
        "Lamb Feet (Paya 1)": "£1.29",
        "Mixed Genuine 100% Goat": "£17.99",
        "Premium Mutton Leg Mince (No Fat)": "£15.99",
        "5Kg Mixed Goat": "£84.95",
        "Half Sheep (15Kg)": "£159.99",
        "Whole Sheep (30Kg)": "£299.99"
    },
    "BEEF": {
        "Whole Fillet Steak Roasting Joint 2.5kg (approx)": "£139.99",
        "Buffalo On the Bone Mixed (1kg)": "£11.99 (Out of stock)",
        "Chilean Wagyu Fillet Steak BMS 6-7 (2 x 150g)": "£79.99",
        "200g Gold Leaf Sirloin": "£12.99",
        "Veal Liver": "£9.99 (Out of stock)",
        "Veal Mince": "£11.99",
        "5 Tariq Halal Beef Sirloin Steak (200 gms each)": "£34.99",
        "Beef Shin On Bone": "£11.99",
        "Beef Topside Steak": "£4.49",
        "Beef Knuckle Steak (3 Steaks)": "£9.99",
        "Beef Mince": "£12.99",
        "Sirloin Steak (whole) Roasting Joint 1kg": "£34.99",
        "Diced Boneless Beef": "£16.99",
        "Beef Short Rib": "£13.99",
        "Beef Oxtail": "£14.99",
        "Fillet Steak (3 Steaks) 600g (3 x 200g)": "£32.99",
        "Bone In Rib-Eye Steak (Each) 350-400g": "£9.99",
        "Boneless Rib-Eye Steak (3 Steaks)": "£22.99",
        "Premium Beef Mince (Ideal For Burgers)": "£15.99",
        "Wagyu Striploin Steak (300g) BMS 8-9": "£69.99",
        "Veal Ossobucu (Shin)": "£14.99 (Out of stock)",
        "Veal Ribeye Steak (3 Steaks)": "£15.99",
        "Beef Marrow Bones 250-300g": "£3.99",
        "Veal Tail": "£12.99",
        "French Trimmed Veal Chop 300-350g": "£9.99",
        "Veal Brain (Whole)": "£5.99 (Out of stock)",
        "Wagyu Tomahawk Steak (BMS 6-7) 1.3-1.5kg": "£99.99 (Out of stock)",
        "Veal T-Bone (Each) 390-410g": "£8.99 (Out of stock)",
        "Cow Foot (Whole)": "£5.99",
        "Veal Topside Steak (3 Steaks) 600g (3 x 200g)": "£15.99",
        "Veal Striploin Steak (3 Steaks)": "£14.99",
        "Veal Fillet Steak (3 Steaks) 600g (3 x 200g)": "£18.99",
        "Diced Boneless Veal": "£19.99",
        "Mixed Veal": "£11.99",
        "T-Bone Steak (300G)": "£9.99",
        "Honeycomb Tripe (Beef)": "£7.99",
        "Tariq Halal Beef Roasting Joint 1kg": "£19.99",
        "Angus Beef Fillet Steak (180-200g)": "£14.99",
        "Angus Sirloin Steak (200-220g)": "£11.99",
        "Angus Boneless Ribeye Steak (200-220g)": "£12.99",
        "Premium Wagyu Beef Bundle Special": "£149.99 (Out of stock)",
        "Santa Rosalia Wagyu Gold Burger (100g x 2)": "£9.99",
        "Santa Rosalia Wagyu Topside Steak (275g)": "£14.99",
        "Santa Rosalia Wagyu Flat Iron Steak (200g)": "£14.99",
        "Santa Rosalia Wagyu Fillet (150g)": "£24.99",
        "Santa Rosalia Wagyu Ribeye (225g)": "£39.99 (Out of stock)",
        "Santa Rosalia Wagyu Striploin (325g)": "£59.99",
        "Dry Aged Ribeye Boneless Steak (av 300g +)": "£12.99 (Out of stock)",
        "Premium Dry Aged Beef Burgers (2 x 180g)": "£7.99 (Out of stock)",
        "Dry Aged Boneless Brisket (280g +)": "£7.99 (Out of stock)",
        "Dry Aged Rump Steak (av 350g)": "£8.99 (Out of stock)",
        "Dry Aged Fillet Steak (av 240g +)": "£10.99 (Out of stock)",
        "Dry Aged Sirloin Steak (290g +)": "£12.99 (Out of stock)",
        "Dry Aged Beef Short Rib (av 350g +)": "£7.99 (Out of stock)",
        "Mollendo Wagyu Striploin Steak Bms 6-7 300g": "£34.99",
        "Beef Topside Strips 1kg": "£17.99",
        "Veal Premium Bacon Pre Sliced (650G)": "£16.99 (Out of stock)"
    },
    "GROCERIES": {
        "Basmati Rice 5kg": "£8.99",
        "Chickpeas 2kg": "£2.99",
        "Lentils 2kg": "£3.49",
        "Cumin Seeds 100g": "£1.50",
        "Turmeric Powder 100g": "£1.00",
        "Garam Masala 100g": "£1.25",
        "Peri Peri Sauce 250ml": "£2.00",
        "Mint Sauce 250ml": "£1.75",
        "Yogurt Sauce 250ml": "£1.50",
        "BBQ Sauce 250ml": "£1.80",
        "Chilli Sauce 250ml": "£1.60",
        "Chapatti Flour 10kg": "£7.50",
        "Plain Naan (2 pieces)": "£1.00",
        "Garlic Naan (2 pieces)": "£1.20",
        "Mango Juice 1L": "£1.50",
        "Pineapple Juice 1L": "£1.50",
        "Mocktail Mojito 330ml": "£1.00",
        "Strawberry Mocktail 330ml": "£1.00",
        "Lychee Drink 330ml": "£1.00",
        "Loose Black Tea 250g": "£2.75",
        "Instant Coffee 200g": "£3.50",
        "Sunflower Oil 1L": "£2.99",
        "Vegetable Oil 1L": "£2.75",
        "Desi Ghee 500g": "£4.50",
        "Toilet Roll 9 Pack": "£3.99",
        "Kitchen Roll 2 Pack": "£2.50",
        "Bin Bags 20pcs": "£1.99",
        "Tandoori Roti (5 pieces)": "£1.20",
        "Sweet Buns Pack": "£1.50"
    },
    "FROZEN MEATS": {
        "Halal Frozen Grade A Chicken (800g)": "£3.99",
        "Frozen Halal Whole Turkey": "£34.99 (CANNOT BE PREORDERED)",
        "Halal Frozen Whole Duck (2.8-3.0kg)": "£24.99",
        "Frozen Halal Duck Legs (2 pieces)": "£9.99",
        "Frozen Halal Duck Breast (1 Piece)": "£8.99",
        "Frozen Halal Duck Feet (1kg)": "£4.99",
        "Frozen Halal Rabbit (whole)": "£19.99",
        "Frozen Halal Quails (4)": "£8.99",
        "Frozen Halal Pigeon": "£14.99 (Out of stock)",
        "Frozen Halal Buffalo Meat (1kg)": "£11.99 (Out of stock)"
    },
    "EXOTIC MEATS": {
        "Whole Frozen Milk Fed Suckling Lamb Shoulder": "£19.99 (Out of stock)",
        "Whole Frozen Milk Fed Suckling Lamb Leg": "£19.99",
        "Whole Kid Goat (4Kg-5Kg)": "£95.00",
        "Whole Baby Lamb (20kg Net Differs)": "£299.99",
        "Haqeeqa Baby Lamb": "£350.00",
        "Haqeeqa Sheep": "£350.00",
        "Lamb Testicles (Kapoorae)": "£7.99",
        "Lamb Brain (Per Packet)": "£7.49",
        "Lamb Feet (Paya)": "£1.29",
        "Lamb Tripe (Stomach)": "£2.00",
        "Lamb Tongue": "£9.99",
        "Lamb Head Without Skin": "£4.99",
        "Veal Tail": "£12.99",
        "Veal Brain (Whole)": "£5.99 (Out of stock)",
        "Veal T-Bone (390-410g)": "£8.99 (Out of stock)",
        "Cow Foot (Whole)": "£5.99",
        "Beef Marrow Bones (250-300g)": "£3.99",
        "Honeycomb Tripe (Beef)": "£7.99",
        "Chicken Feet (1kg bag)": "£4.99",
        "Chicken Gizzards (1Kg)": "£5.99",
        "Chicken Hearts (1Kg)": "£5.99",
        "Chicken Liver (1Kg)": "£5.99"
    },
    "MARINATED MEATS": {
        "CHICKEN": {
            "Truffle Chicken Cubes (1kg)": "£9.99",
            "Mumtaz Lemon Pepper & Herb Wings (1kg)": "£8.99",
            "Dragons Fire Chicken Niblets": "£8.99",
            "Mumtaz Peri Peri Wings 1kg": "£8.99",
            "Mumtaz Chicken Tikka Cubes 1kg": "£9.99",
            "CHICKEN SHAWARMA": "£9.99",
            "MARINATED DRUMSTICKS": "£5.99",
            "JERK CHICKEN LEGS": "£5.99",
            "LEMON & CHILLI Chicken Fillets": "£9.99",
            "MARINATED CHICKEN CUBES": "£9.99",
            "Marinated Baby Chicken": "£6.49",
            "Exotic Mango & Chilli Drumsticks": "£5.99",
            "Fire In The Hole Wings (20 pieces)": "£8.99",
            "PERI PERI Wings": "£7.99",
            "FIRE IN THE HOLE MEAT BOX": "£39.99",
            "Greek Chicken Gyros (kebab)": "£5.99",
            "Spicy Mexican Fajita Chicken Strips": "£9.99",
            "Italian Green Pesto Chicken": "£9.99"
        },
        "LAMB": {
            "Truffle Lamb Chops (1kg)": "£24.99",
            "Mumtaz Sticky BBQ Lamb Ribs 1kg": "£11.99",
            "Mumtaz Lamb Chops 1kg": "£24.99",
            "MARINATED LAMB RIBS": "£11.99",
            "LAMB SHAWARMA": "£19.99",
            "Greek Lamb Gyros (kebab)": "£10.99",
            "Hot & Spicy Lamb Chops": "£24.99"
        },
        "BEEF": {
            "MARINATED BEEF T-BONE": "£11.99",
            "Marinated Sirloin Steak": "£9.99",
            "Fire In The Hole Beef Ribs": "£14.99"
        },
        "COMBOS": {
            "COMBO - Greek Chicken & Lamb Gyros (kebab) 1kg": "£12.99"
        }
    }
}

